noironetworks/apicapi

etc/apic.sh
fix: we need run apic.sh only for root users
=> fix: we need run apic.sh only for root users

apicapi/apic_manager.py, apicapi/config.py
=> Add config option for per-tenant NAT EPG

apicapi/apic_manager.py
Also fixed a bug in a similar function when
unsetting the VRF association.
=> Add method for setting VRF for a BD

apicapi/apic_manager.py
Added support for FEX port-name convention
=> Added support for FEX port-name convention

apicapi/apic_manager.py, apicapi/config.py, apicapi/tests/unit/test_apic_manager.py
Partially closes noironetworks/support#333
=> Read apic_vpc_pairs correctly in new-style config

apicapi/apic_manager.py, apicapi/tests/unit/test_apic_manager.py
Cisco IT wants to assign an AEP in the config file then automatically
those vmm domains will be associated with this AEP even when
provision_infra is false. I also added a check to make sure such
AEP does exist in such mode.
=> Set AEP for domains even when provision_infra is false.

apicapi/apic_manager.py
All the UTs will be in the MD area and I will submit that
right after this patch.
=> Just add an API to support the nameAlias update

apicapi/apic_mapper.py
This is to support getting tenant name change notifications
from keystone in our MDs.
=> Add a few tenant-related APIs

apicapi/apic_client.py, apicapi/tests/unit/test_apic_client.py
=> Add definitions for service-graph objects

apicapi/apic_client.py
Fix unintended space in bgpExtP resource
=> Fix PEP8 error

apicapi/apic_domain.py
=> Support multiple VLAN ranges in domain

setup.py
In order to accomodate branch releases, rebase the
master branch semantic version.
=> Rebase semantic version

rpm/apicapi.spec.in, rpm/bondwatch.service
Please check and merge. I still need a system without containers to test it.
=> Adding service for bond-watch

apicapi/tools/host_report.py
Signed-off-by: Tom Flynn <tom.flynn@gmail.com>
=> Add call to retrieve any unresolved relations in opflex MODB.

apicapi/tools/host_report.py
=> Vergtihash

apicapi/apic_client.py
=> Add netflow

apicapi/apic_client.py
MOs to enable ERSPAN functionality.
- Creating VSPAN sessions using Source vspan and Destination vspan groups.
=> Add MOs for ERSPAN functionality

apicapi/apic_client.py
=> Support for epg subnet

apicapi/apic_client.py
To support normalization of remoteIPs. We need to add support for the new MOs introduced in ACI.
=> Adding feature support for remoteIP Container

apicapi/apic_client.py
(cherry picked from commit b6b51c555e2171a3e4ff1605e3cae232c661305b)
=> Adding RemoteIPContainer mo support

apicapi/apic_client.py
This reverts commit b6b51c555e2171a3e4ff1605e3cae232c661305b.
(cherry picked from commit 07d0575f00c4f08aa388a48cb36b0a7986de42b8)
=> Revert "Adding RemoteIPContainer mo support"

setup.py
(cherry picked from commit 2ca0b347a294f85de8070fd7b94ccb603118cc51)
=> Bumping version to 1.11.0

rpm/pipeline-rpm-script, rpm/sign-rpm.sh
- added capability to sign apicapi rpms
=> updated pipeline script

rpm/apicapi.spec.in
Python3 builds should have the python3- prfiex.
=> Fix python3 packaging
