apicapi/apic_client.py, apicapi/apic_manager.py, apicapi/config.py, apicapi/exceptions.py, apicapi/tests/unit/test_apic_manager.py
1. support vmm type VMware in addition to OpenStack
2. define a new config item apic_vmm_type (either OpenStack or VMware, defaults to OpenStack) 
3. introduce 2 new exception classes 
4. added 3 test cases for this feature work
=> vmware integration feature

apicapi/apic_client.py, apicapi/apic_manager.py, apicapi/config.py, apicapi/tests/unit/common/test_apic_common.py, apicapi/tests/unit/test_apic_manager.py
If there are external networks configured, create
external-routed domain, attachable entity-profile,
function profile and access-port selectors.
Signed-off-by: Amit Bose <bose@noironetworks.com>
=> Add support for external-routing domain objects

apicapi/apic_manager.py
This small change fixed a problem we had when restarting the neutron-server.
Thanks!
=> Preventing apic manager to push default configuration when ports are blank

apicapi/apic_domain.py, apicapi/tests/unit/test_apic_manager.py
1. if the vmm_type is vmware, don't need to create the extra openStack vmm domain
inside create() because we already inserted this extra openStack vmm domain during
the retrieve_domains() call.
2. add a test case for the above case.
=> fix a bug which breaks the vmware vmm domain integration

apicapi/apic_domain.py, apicapi/apic_manager.py, apicapi/config.py, apicapi/tests/unit/common/test_apic_common.py, apicapi/tests/unit/test_apic_config.py, apicapi/tests/unit/test_apic_manager.py
* Added an option to indicate the encapsulation mode
to use for a VMM/physical domain ('encap_mode'). If
unspecified, the encap mode is guessed from other
config options like we do today.
* Added section 'apic_physical_network:<net-name>' which
can be used to associate individual server nodes to
logical segments in the physical network. The format
of options in this section is -
hosts=<comma-separated list of hosts>
segment_type=...
Partially-Closes noironetworks/support#113
=> Add config options to apicapi for physical nodes

apicapi/apic_domain.py
ML2 allows physnet without vlan's as vlan_ranges. Skip them for apicapi.
=> Skip vlan_ranges with no vlans

apicapi/apic_manager.py, apicapi/tests/unit/test_apic_manager.py
For consistency with apic_domain usage of vlan_ranges with no vlans,
updated logic on apic_manager as well
=> Updated apic_manager vlan config for no vlans

apicapi/apic_client.py, apicapi/tests/unit/test_apic_client.py
Enhanced the regular expression in DN manager to support
limited form of nesting of square brackets. Won't
support arbitrary levels of nesting (which would require
a proper parser), but it should be sufficient to support
current use-cases (for example, DNs of EPG static path binding
objects).
=> Allow DN-manager to parse RNs with nested square brackets

apicapi/apic_manager.py, apicapi/config.py
If user changes the exchange or topic udner keystone.conf then
they have to change these 2 parameters accordingly.
=> Introduce 2 config parameters for keystone notifications

apicapi/apic_client.py
For testability purposes, calling post_body_dict will make the
body attributes order irrelevant
=> Call post_body_dict from transactions instead of post_body

apicapi/apic_client.py, apicapi/tests/unit/test_apic_client.py
Mainly deals with management of DNs
that are not under polUni 'uni'. Some of the
transaction stuff also needs to be updated
but haven't done that here since all (?)
non-uni objects are read-only.
=> Allow handling of objects not under 'uni/'

apicapi/apic_client.py, apicapi/tests/unit/test_apic_client.py
AID should be able to ignore the faults generated with this parent
now.
=> Rollback incomplete vnsConfigIssue support

apicapi/apic_manager.py, apicapi/config.py, apicapi/tests/unit/common/test_apic_common.py, apicapi/tests/unit/test_apic_manager.py
1. Here is an example of the new config. Note the pod_id and
eth1/eth2 parameters which are the new things added.
[apic_switch:401]
pod_id=2
f4-compute-2.noiro.lab|eth1=1/34
f4-compute-1.noiro.lab|eth2=1/33
2. Also add the UTs for this which were compeltely missing before.
3. Also test it out on the real fab for both unified and legacy
plugins to make sure the same set of APIs can support both DB schemas.
=> Allow different pod_id and interface_name from the config file

apicapi/apic_manager.py
The logic to remove any other links from the same host doesn't make sense any more
once we start to support multiple host links thru config file option.
=> Enable multiple host links support for legacy plugin.

apicapi/apic_manager.py, apicapi/tests/db/apic_model.py
The ApicDbModel was changed in commit 18997b2c1686c12046ec6d7200102e6fcaafc878
to prevent the use of cached sessions. The apicapi library gets passed this model,
and therefore needs to use the new getter method provided to use non-cached sessions.
=> Don't use cached sessions

requirements.txt
The newer versions no longer have MultiConfigParser, which apicapi
uses.
=> Set upper bound on oslo.config

apicapi/tools/host_report.py
The agent-ovs program was renamed opflex-agent, so the host report
needs to use the new name when collecting output from journalctl.
=> Fix host-report for agent rename

apicapi/tools/bondwatch.py, debian/apic-bond-watch.service, rpm/apic-bond-watch.service
Get the bond interface from an environment variable, or else
use the default of bond0.
=> Get bond interface from environment

apicapi/apic_client.py, apicapi/tests/unit/test_apic_client.py
The code to recover from authorization or login failures with
APIC only considers 403 HTTP response codes. This patch adds
the 401 HTTP response code (this was seen when APIC lost its
connection with the AAA server).
=> Fix re-login to APIC

apicapi/apic_client.py
- Removed fvCEp since it was not needed for our usecase.
- Added infraRsSpanVSrcGrp__ap which uses acc port group.
- Removed infraRsSpanVDestGrp since it was not needed for our use case.
=> Updated ERSPAN Mos

apicapi/apic_client.py
- We need these two MOs for successfully binding destination groups.
=> Add MOs for ERSPAN VPC

rpm/apicapi.spec.in, rpm/build-rpm.sh
Update package names in order to build packages that support both
RHEL7 and RHEL8 for python2.
=> Support python2 builds for RHEL7/8

rpm/build-rpm.sh
The click package dependency needs to reference the python3 version.
=> Fix for python3 RPM packaging

apicapi/apic_manager.py, apicapi/apic_mapper.py, apicapi/tools/bondwatch.py, apicapi/tools/cli/common.py, apicapi/tools/cli/neutron/client.py, apicapi/tools/cli/shell.py
In python3, exceptions no longer have a "message" property. Code
that uses the message property must just use the string representation
of the exception, in order to be compatible with both python2 and
python3.
=> Fix exception messages for python3

apicapi/tests/unit/_test_shell.py, apicapi/tools/cli/shell.py
- Exposing erspan functionality through apic cli.
- Erspan create Usage: apic erspan-create [OPTIONS]
Options:
--neutron_port   Neutron port uuid
--dest_ip            destination ip address
--flow_id            Flow Id
- Erspan delete Usage: apic erspan-delete [OPTIONS]
Options:
--neutron_port   Neutron port uuid
=> Erspan integration with apic cli

test-requirements.txt
The upstream cryptography packages changed, causing failures in
depednencies for python3.
=> Fix requirements to support cryptography changes

apicapi/apic_manager.py
Allow for longer system ID lengths. This is done to support existing deployments that used long system IDs, but don't use any MOs that require the shorter name length.
=> Allow for longer system IDs

debian/build-deb.sh, debian/control, debian/rules
Python2 is EOL, so remove support for it in debian builds.
=> Remove python2 support for debian
